import os
import json
import re
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path("d:/Claudcoude/projetos/adega")
WORKSPACE = ROOT / "workspace"
FINDINGS_DIR = WORKSPACE / "findings"
REPORT_DIR = WORKSPACE / "report"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

STATE_PATH = WORKSPACE / ".mantis_state.json"
pass_num = 1
snapshot_id = "live-tree"
snapshot_pinned = False
vcs_info = {"vcs_type": "git", "branch": "master", "commit_hash": "e1ae7db", "dirty": False}

if STATE_PATH.exists():
    state_data = json.loads(STATE_PATH.read_text(encoding="utf-8"))
    pass_num = state_data.get("pass_number", 1)
    active = state_data.get("active_snapshot", {})
    snapshot_id = active.get("snapshot_id", "live-tree")
    snapshot_pinned = active.get("snapshot_pinned", False)
    vcs_info = state_data.get("vcs_info", vcs_info)

now_iso = datetime.now(timezone.utc).isoformat()

# Load all findings
findings = []
for p in FINDINGS_DIR.glob("*.json"):
    if p.is_file() and not p.name.startswith("."):
        try:
            data = json.loads(p.read_text(encoding="utf-8"))
            findings.append(data)
        except Exception:
            pass

# Sort by risk score descending
findings.sort(key=lambda x: x.get("mantis_risk_score", 0), reverse=True)

# Generate report content
report_lines = []

# Disclaimer & Header
report_lines.append("# Adega Cloud — Security Review Packet\n")
report_lines.append("> **DISCLAIMER:** This report was automatically generated by Mantis AI. All findings and patches are AI-generated and must be manually verified by a security or subject matter expert before deployment or disclosure.\n")

report_lines.append("## Target Provenance")
report_lines.append(f"- **Target Version:** Git branch `{vcs_info.get('branch', 'master')}` at commit `{vcs_info.get('commit_hash', 'e1ae7db')}`")
report_lines.append(f"- **Snapshot ID:** `{snapshot_id}` (pinned: `{snapshot_pinned}`)")
report_lines.append(f"- **Pipeline Pass:** `Pass {pass_num}`")
report_lines.append(f"- **Report Timestamp:** `{now_iso}`\n")

# Executive Summary Table
report_lines.append("## Executive Summary\n")
report_lines.append("| ID | Title | Risk Score | Priority | Viability | Exposure | Status |")
report_lines.append("| --- | --- | --- | --- | --- | --- | --- |")

for f in findings:
    f_id = f.get("id")[:8]
    title = f.get("title")
    score = f.get("mantis_risk_score", "N/A")
    priority = f.get("priority", "N/A")
    viability = f.get("production_viability", "N/A")
    exposure = f.get("inferred_exposure", "N/A")
    status = f.get("status", "N/A")
    report_lines.append(f"| `{f_id}` | {title} | `{score}` | `{priority}` | `{viability}` | `{exposure}` | `{status}` |")

report_lines.append("\n---\n")

# Category 2 / 3: Detailed Vulnerability Findings
report_lines.append("## Verified Vulnerability Findings\n")

for idx, f in enumerate(findings, 1):
    report_lines.append(f"### Finding {idx}: {f.get('title')}")
    report_lines.append(f"- **Finding ID:** `{f.get('id')}`")
    report_lines.append(f"- **Discovery Snapshot:** `{f.get('discovery_commit', '(not recorded)')}`")
    report_lines.append(f"- **CWE:** `{f.get('cwe', 'N/A')}`")
    report_lines.append(f"- **Risk Score:** `{f.get('mantis_risk_score', 'N/A')}` / 10.0 (`{f.get('priority', 'N/A')}`)")
    report_lines.append(f"- **Production Viability:** `{f.get('production_viability', 'N/A')}`")
    report_lines.append(f"- **Attacker Position:** `{f.get('attacker_position', 'N/A')}` | **Inferred Exposure:** `{f.get('inferred_exposure', 'N/A')}`")
    report_lines.append(f"- **Code Paths:** `" + ", ".join([f"`{cp}`" for cp in f.get('code_paths', [])]) + "`\n")
    
    report_lines.append("#### Description & Impact")
    report_lines.append(f"{f.get('description')}\n")
    report_lines.append(f"**Impact:** {f.get('impact')}\n")
    
    report_lines.append("#### Validation & Critic Rationale")
    report_lines.append(f"- **Validation Reasoning:** {f.get('reasoning')}")
    report_lines.append(f"- **Critic Viability Analysis:** {f.get('critic_reasoning')}")
    report_lines.append(f"- **Sanity Triage Applied:** `{f.get('sanity_triage_applied')}`\n")
    
    report_lines.append("#### Mitigation Strategy")
    report_lines.append(f"{f.get('mitigation')}\n")
    
    if f.get("repro_hints"):
        report_lines.append("#### Reproduction Hints")
        report_lines.append(f"```text\n{f.get('repro_hints')}\n```\n")
        
    report_lines.append("---\n")

report_lines.append("## Appendix: Low Priority Findings")
report_lines.append("- No low-priority findings recorded in this pass.\n")

# Tagged output path
clean_tag = re.sub(r'[^A-Za-z0-9.-]', '_', snapshot_id)
out_tagged_path = REPORT_DIR / f"review_packet_pass_{pass_num}_{clean_tag}.md"
out_latest_path = REPORT_DIR / "review_packet-latest.md"

full_text = "\n".join(report_lines)
out_tagged_path.write_text(full_text, encoding="utf-8")
out_latest_path.write_text(full_text, encoding="utf-8")

# Update state
if STATE_PATH.exists():
    state_data["current_stage"] = "mantis-report"
    state_data["completed_stages"].append("mantis-report")
    state_data["last_updated"] = now_iso
    STATE_PATH.write_text(json.dumps(state_data, indent=2), encoding="utf-8")

print(f"Mantis Report generated successfully at:\n- {out_tagged_path}\n- {out_latest_path}")
